### ISSUE TITLE
installation of Rancher for K8s cluster is broken

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#122]
All this worked on 16th Oct'20. However, yesterday/today jetstack.io stopped providing their helm repo at https://charts.jetstack.io 

![Screenshot 2020-09-18 at 11 21 44](https://user-images.githubusercontent.com/353767/93581278-37d55480-f9a1-11ea-9cda-6719db6b393c.png)

and are instead redirecting to  https://hub.helm.sh

![Screenshot 2020-09-18 at 11 21 52](https://user-images.githubusercontent.com/353767/93581295-3f94f900-f9a1-11ea-9797-823d3dc14494.png)

However, `helm repo add jetstack https://charts.jetstack.io` can't handle the redirect and fails. This, in turn, breaks the installation of Rancher for K8s cluster.

```
2020-09-18 09:10:06,984 - INFO - docker_machine_connector.py:585 - Install COE manager Rancher.
2020-09-18 09:10:15,752 - ERROR - docker_machine_connector.py:593 - Failed to install COE manager Rancher: cmd returned error 1: + set -e
+ export KUBECONFIG=/home/ubuntu/.kube/config
+ KUBECONFIG=/home/ubuntu/.kube/config
+ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+ chmod 700 get_helm.sh
+ sudo ./get_helm.sh
+ helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
+ kubectl create namespace cattle-system
+ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.0/cert-manager.crds.yaml
+ kubectl create namespace cert-manager
+ helm repo add jetstack https://charts.jetstack.io
Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "serverInfo"
exit status 1
```

**Comment by konstan** [comment]
The issue is due to this bug https://github.com/helm/helm/issues/8761 in helm that appeared 13 hours ago. They already produced a fix and are working on the validation of the PR https://github.com/helm/helm/pull/8762. Not all helm repos are affected; however, `https://charts.jetstack.io` that I need - is affected.

I'm using `sudo ./get_helm.sh` w/o `--version ...` to install the latest version of helm (3.3.2 at the moment). But even if I used it with the version, `./get_helm.sh` fails to validate checksum ... 🤦  (including other releases).

```
root@nuvla-690762a5-34fe-4085-831d-004ba424eb33-k8s-manager-1:/home/ubuntu# ./get_helm.sh --version 3.3.1
Helm 3.3.1 is available. Changing from version v3.3.2.
Downloading https://get.helm.sh/helm-3.3.1-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-oUE4S3/helm-3.3.1-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: --version 3.3.1
Accepted cli arguments are:
        [--help|-h ] ->> prints this help
        [--version|-v <desired_version>] . When not defined it fetches the latest release from GitHub
        e.g. --version v3.0.0 or -v canary
        [--no-sudo]  ->> install without sudo
        For support, go to https://github.com/helm/helm.
root@nuvla-690762a5-34fe-4085-831d-004ba424eb33-k8s-manager-1:/home/ubuntu#
```

Result: I will not do anything with this now and simply wait for the fix to https://github.com/helm/helm/issues/8762 and release 3.3.3 of helm.

**Comment by bacongobbler** [comment]
> But even if I used it with the version, `./get_helm.sh` fails to validate checksum

You're providing the wrong arguments. Use `./get_helm.sh --version v3.3.1` (notice the "v").

**Comment by konstan** [comment]
@bacongobbler 👍  Thank you for the hint! 
I was confused because the part of the script which downloads the tarball is happy with the value.

**Comment by konstan** [comment]
Closing. Helm fixed the issue.
