### ISSUE TITLE
do not queue jobs that have provisioning-mode=pull

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/job-engine#130]
~~these should go straight to `state`=WAITING~~
these should go straight to `state`=QUEUED

**Comment by 0xbase12** [comment]
Deployment in push mode will dictate the execution-mode.
For NB actions, an input option should specify the execution-mode of the job

**Comment by 0xbase12** [comment]
This task should be on api-server

**Comment by cjdcordeiro** [comment]
in fact this ticket is not needed anymore since the `execution-mode` is enough. the api-server doesn't need to do anything. 

I think all is needed is a new conditional, here: https://github.com/nuvla/job-engine/blob/master/code/src/nuvla/job/job.py#L49

like:
```
elif self.get('execution-mode') == 'pull':
 skip
```

**Comment by 0xbase12** [comment]
I think we should not put job-id in zookeeper queue if execution mode is a pull. Since this is done on api-server ...

**Comment by cjdcordeiro** [comment]
hum...yes that's another way to do it, for sure, but in that case how do you handle "mixed"?

**Comment by 0xbase12** [comment]
Api-server: I put in the queue. So the job goes to job-engine.  (Try push)
Job-engine: If an error occur, change execution-mode to "pull" and delete job from queue as if it was a success

**Comment by cjdcordeiro** [comment]
sounds good
