### ISSUE TITLE
Add ability to start the job-executor for a specific pull-mode job execution (instead of zookeeper)

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/job-engine#133]

**Comment by cjdcordeiro** [comment]
as a reference:

<img width="567" alt="Screen Shot 2021-01-05 at 11 17 04 AM" src="https://user-images.githubusercontent.com/4047767/103634647-a980e080-4f47-11eb-8e95-431d58f29f05.png">

**Comment by schaubl** [comment]
Done
