### ISSUE TITLE
when running a pull mode job, the job-engine(-lite) must keep the necessary apikey on disk

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/job-engine#142]
to be used for subsequent automated jobs (like deployment_update) and for coping with unexpected early terminations of a job, to be picked up later

**Comment by 0xbase12** [comment]
While working on telemetry response with jobs I got this idea. 
The telemetry is a simple edit on NB status resource. Putting the list of jobs in the response is not standard.
I propose to change this to https://github.com/nuvlabox/agent/blob/master/code/app.py#L168:
- while true
  - ...
  - Update telemetry
  - If no job in execution
    - Query jobs (order=created:desc, target-resource="<nb-id>", filter="execution-mode='pull', last=1"
    - do action if any
    -  get job context which is a new operation on api-server which will fetch all needed resources and send them in the response

**Comment by cjdcordeiro** [comment]
there are 2 problems with this approach

1. the additional query to Nuvla
2. the propagation of secrets. If a job needs additional credentials (ie. registry), the agent would need to do a lot os subsequent queries to find out the needed keys. Also in this case, we would need to assume that whatever credentials are needed, the NB API key can view them

**Comment by 0xbase12** [comment]
Update of NB status should happen at same interval during the execution of an action. I think you agree with that.
Server is doing at each telemetry write get jobs (so queries are running on server at each update even if an action is already in progress). So more queries.
In the way I propose, the agent ask to get a job when he is not running an action.
Second advantage, we don't store secrets on disk in case of failure  #142
So the agent can ask the context to run the job on the job resource. Which will be smart enough to send all needed resources including credentials and registries

**Comment by cjdcordeiro** [comment]
> Update of NB status should happen at same interval during the execution of an action

yes, which is one more reason not to pipe any additional calls on the agent which might delay the execution of the next telemetry cycle

> Server is doing at each telemetry write get jobs (so queries are running on server at each update even if an action is already in progress). So more queries.

y we'll always need more queries. But it is better to have them server-side

> In the way I propose, the agent ask to get a job when he is not running an action.

Is the advantage to keep the server from doing a query for pull-mode jobs on every telemetry cycle? If so, then yes, this could be an improvement, but I don't think it outweights the need to keep the agent as simple as possible

> Second advantage, we don't store secrets on disk in case of failure #142

you need to anyway, at least for deployment_update jobs

> So the agent can ask the context to run the job on the job resource. Which will be smart enough to send all needed resources including credentials and registries

again this would imply more queries on the agent, which I'd rather avoid

**Comment by 0xbase12** [comment]
What do you need to store for deployment_update jobs?

**Comment by cjdcordeiro** [comment]
which job context? remember that the deployment_update jobs are not distributed in Nuvla anymore, but by the job-engine-lite locally

**Comment by 0xbase12** [comment]
Yes, for that I proposed to add an operation on job resource to be able to get all needed resources that can't be accessed directly by the job-engine-lite session and I called it get-context.

**Comment by cjdcordeiro** [comment]
I think there's a gap somewhere.

 -> The job-engine-lite is running on a remote IS. -> it get a deployment_start job, and executes it -> on every telemetry cycle, the nuvlabox will scan the IS for active NUVLA deployments and submit a local deployment_update job for each one -> the job-engine-lite executes those jobs, **but where does it get the deployment apikey from**, since the job was created locally?

**Comment by 0xbase12** [comment]
By deployment_update job you mean the deployment_state ?

**Comment by cjdcordeiro** [comment]
oh sorry yes...yes update...wrong name

**Comment by 0xbase12** [comment]
You want to get rid of deployment state distributor also for deployments in pull mode. Ah okey. Thinking about that... and will get back to you

**Comment by cjdcordeiro** [comment]
it was one idea...so that we don't blindly spawn pull-mode jobs in the server. 

but I understand the job-context action. It is a good idea, as long as it doesn't affect the agent nor causes the NB to issue too many GET requests from Nuvla

**Comment by cjdcordeiro** [comment]
not needed for now, since deployment_state jobs are still being distributed by the api-server, and `get-context` will fetch the necessary keys every time
