### ISSUE TITLE
adapt job actions to work with pull-mode jobs

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/job-engine#151]

**Comment by cjdcordeiro** [comment]
for NB only

## actions

 - `nuvlabox_add_ssh_key.py`: the NB API key does not have view access to other credential, including the user's SSH creds -> https://github.com/nuvla/job-engine/blob/master/code/src/nuvla/job/actions/nuvlabox_add_ssh_key.py#L33
 - `nuvlabox_decommission.py`: this can only run in the server, never in pull-mode
 - `nuvlabox_releases.py`: this can only run in the server, never in pull-mode
 - `nuvlabox_revoke_ssh_key.py`: the NB API key does not have view access to other credential, including the user's SSH creds -> https://github.com/nuvla/job-engine/blob/master/code/src/nuvla/job/actions/nuvlabox_revoke_ssh_key.py#L33
 - `nuvlabox_update.py`: this can only run in pull-mode, otherwise it will stall the api-server (updates take time)

...

**Comment by 0xbase12** [comment]
`deployment_*.py` done
`nuvlabox_add_ssh_key` done
`nuvlabox_revoke_ssh_key` done
