### ISSUE TITLE
Do not fail the update if "installation-parameters" are missing

### ISSUE THREAD

**Issue by schaubl** [nuvla/job-engine#164]
https://github.com/nuvla/job-engine/blob/8de91ac62486057b6668b70566c56888d07baf4d/code/src/nuvla/connector/nuvlabox_connector.py#L206-L209

**Comment by cjdcordeiro** [comment]
given that this can not be handle by the job-engine, the only solution is to allow passing the `payload` attr to the job, where the user can manually define the old installation-parameters

**Comment by cjdcordeiro** [comment]
re-assigning to @0xbase12 . Once the UI part is done I can take over for the job-engine

**Comment by 0xbase12** [comment]
`update_nuvlabox` action will allow to send an optional `payload` parameter of type string that contains a json string. 

In the UI the update action will show a form with installation-parameters only for NuvlaBoxes < 1.14 ? Or always show these fields.

Installation parameters are: 
- working-dir - string
- config-files - array of string
- project-name - string 
- environment - array of string

**Comment by cjdcordeiro** [comment]
> In the UI the update action will show a form with installation-parameters only for NuvlaBoxes < 1.14 ? Or always show these fields.

always show, but as an optional&advanced body


wrt the params, that's it

**Comment by 0xbase12** [comment]
<img width="908" alt="Screenshot 2021-02-18 at 14 08 05" src="https://user-images.githubusercontent.com/5518233/108361476-d5ec7580-71f2-11eb-9809-6757e731b15c.png">
<img width="899" alt="Screenshot 2021-02-18 at 14 08 36" src="https://user-images.githubusercontent.com/5518233/108361490-d97ffc80-71f2-11eb-8cae-85c42d356939.png">
