### ISSUE TITLE
there is an issue with running job-engine light image on certain platforms due to seccomp

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#218]
Hence, the currently tested and working combination is python:3.8-alpine3.12 and is pinned here https://github.com/nuvla/job-engine/blob/master/container-lite/Dockerfile#L1

Changing this base image tag is not recommended until testing of the container is done on all the target platforms.

Reference https://docs.docker.com/engine/security/seccomp/

**Comment by konstan** [comment]
Here is an example of the failure on another combination of python/alpine.
```
root@raspberrypi:~# docker run -it --rm python:3.10-alpine3.14 sh
/ # python
Python 3.10.0 (default, Oct  6 2021, 03:51:47) [GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```

**Comment by schaubl** [comment]
Do not apply anymore
