### ISSUE TITLE
extend K8s driver to provide logs of all containers from Pods part of resource kinds other than Deployment

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#236]
At the moment only Deployment is supported. We need:

- [x] Deployment
- [x] Job
- [x] StatefulSet
- [x] DaemonSet
- [x] CronJob

**Comment by konstan** [comment]
Related https://github.com/nuvla/ui/issues/741 UI change.

**Comment by konstan** [comment]
Clarify the list of the high-level objects that create pods (and eventually containers) that generate logs.

**Comment by konstan** [comment]
Here is the list of the [workload type objects](https://kubernetes.io/docs/concepts/workloads/controllers/) that create pods with containers 

- Deployment
- StatefulSet
- DaemonSet
- CronJob
- Job

So, this is the potential list of the object kinds user may create.

With the idea, that UI would provide the full path to the container. E.g.: `CronJob/my-cronjob/my-pod/container-1`, `Job/my-job/my-pod/container-1`, `Deployment/my-deployment/my-pod/container-25`

**Comment by konstan** [comment]
When listing "services", we always have to return the full tree down to the containers. Also, the logs retrieving code must be updated to always work on the level of containers.

**Comment by konstan** [comment]
@giovannibianco I created Deployment, StatefulSet, DaemonSet, CronJob, Job apps for testing. They can be found here
https://nuvla.io/ui/apps/examples/k8s-test-apps?apps-project-tab=overview

**Comment by giovannibianco** [comment]
We can demo the Deployment logs...
