### ISSUE TITLE
on k8s app do not attempt to provide Service object logs

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#269]
At the moment, the Service object is shown on the logs tab on UI.

![Screenshot 2023-05-25 at 15 38 17](https://github.com/nuvla/job-engine/assets/353767/9e03d9b8-57d7-47f1-bd98-215b665544ad)

**Comment by giovannibianco** [comment]
Fixed by https://github.com/nuvla/job-engine/pull/272

**Comment by giovannibianco** [comment]
See above... already fixed.
