### ISSUE TITLE
Timeout when deploying with docker-compose ...

### ISSUE THREAD

**Issue by schaubl** [nuvla/job-engine#92]
... a docker image that takes time to download on a slow internet connection.

The timeout should be increased because on edge devices the internet connection can be very slow.

If possible it would be better to ignore or having a much bigger timeout during image download.

**Comment by cjdcordeiro** [comment]
the timeout doesn't happen because of docker-compose but because of the remote docker connection to the IS API endpoint. 

With the introduction of pull-mode jobs, this issue is no longer relevant since long lasting jobs should always go in pull-mode

**Comment by cjdcordeiro** [comment]
issue still happens in pull mode cause docker-compose fixes the timeout whenever -H is used, and it still is

Fix: pull all images before running docker-compose

**Comment by cjdcordeiro** [comment]
@schaubl can u confirm whether this has been fixed already?
